const mongoose=require('mongoose')
const OrderModelSchema=new mongoose.Schema({
    buyerId:{
        required:true,
        type:mongoose.Types.ObjectId,
        ref:"FoodDeliveryUser",
    },
    cartItems:[
        {
            type:mongoose.Types.ObjectId,
            ref:"FDCart"
        }
    ],
    subTotal:{
        type:Number,
        required:true
    },
    disocunt:{
        type:Number,
        min:0,
        default:0
    },
    deliveryCharge:{
        type:Number,
        default:150
    },
    tax:{
        type:Number
    },
    total:{
        type:Number,
        required:true,
    },
    status:{
        type:String,
        enum:["pending","confirmed","cancelled","completed"],
        default:"pending"
    },
    isPaid:{
        type:Boolean,
        default:false,
    },
    createdBy:{
        type:mongoose.Types.ObjectId,
        ref:"FoodDeliveryUser",
        default:null
    },
    updatedBy:{
        type:mongoose.Types.ObjectId,
        ref:"FoodDeliveryUser",
        default:null
    }
},{
    timestamps:true,
    autoCreate:true,
    autoIndex:true
})
const OrderDb=mongoose.model("FDorder",OrderModelSchema)
module.exports=OrderDb